---
driver:
  name: vagrant
  customize:
    memory: 512

provisioner:
  name: chef_solo

# We use Opscode's base boxes to avoid the chicken/egg problem that would arise
# if we tried to use our own base boxes.
platforms:
  - name: ubuntu-10.04_chef-10.18.2
    driver:
      box: opscode_ubuntu-10.04_chef-10.18.2
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_chef-10.18.2.box
  - name: centos-6.3_chef-10.18.2
    driver:
      box: opscode_centos-6.3_chef-10.18.2
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.3_chef-10.18.2.box
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[minitest-handler]
      - recipe[vagrant_base_box::default]
    attributes:
      vagrant_base_box:
        virtualbox:
          guest_additions:
            # The VirtualBox additions are already deleted from the Opscode
            # base boxes, and .vbox_version is in a different place than ours.
            download: true
            version_file: /home/vagrant/.vbox_version
